### PR TITLE
Refactor socials

### PR DESCRIPTION
**Pull request by mohamadbakri**
modify width and height of social media icons

### CODE REVIEW

**Review by ishimwezachee — CHANGES_REQUESTED** [review]
Hi @mohamadbakri , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Highlights
Linters are passing successfully ✔️
The project is running successfully ✔️

## Required Changes ♻️

- [ ]  You should remove unrequited comments in your index.html file. this make your codes more clean. 
- [ ]  Your Readme file should have a description, the summary of your project and also remove the demo link, for you don't have demo link for now 
image

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by Reem-lab — CHANGES_REQUESTED** [review]
Hi @mohamadbakri,  👋🏻👋🏻

Great work on making the changes requested by a previous reviewer 👏 🔥🔥
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.



 ## Highlights
-  Linters checked passed ✅✅
- follow GitHub flow ✅✅💪🏻


 ## Required Changes ♻️
_Check the comments under the review._
[ Required] I think you didn't add the Hamburger menu icon as the previous code reviewer asked, please Fix it and put icons instead of the background image, you can check this so you can import the icon from there [icons](https://fontawesome.com/)

## Optional suggestions
[OPTIONAL] Kindly fix your background image for the header to suit it because it is important to stick with the Figma design.

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by sumairq** [comment]
Please make sure that your linters are passing.

**Review by sumairq — CHANGES_REQUESTED** [review]
Hi @mohamadbakri , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that does not have all linters passing.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by zhadier — APPROVED** [review]
## Hi @mohamadbakri  👋  

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 

# Congratulations! 🎉 

### Keep Rocking!👏👏👏
## Optional
<hr/>

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
