### PR TITLE
style supporting text

### PR DESCRIPTION
**Pull request by mohamadbakri**
restyling supporting text

### CODE REVIEW

**Review by koachcode — CHANGES_REQUESTED** [review]
Hi @mohamadbakri , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has no linters check, and also you have to proper PR description. Fix your linters 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by mohamadbakri** [comment]
linters is setup

**Comment by Ginohmk** [comment]
@mohamadbakri Please follow this [guide](https://github.com/Ginohmk/linters-config/tree/master/html-css) to set up your linters, run all commands found here, and please make sure you have all files from the `.github/workflows` in your project with same folder name, structure, and contents(linter.yml).

**Comment by mohamadbakri** [comment]
navigate the repo please dont say any words

**Pull request closed without merging**
